# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\finance.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowFinance(object):
    def setupUi(self, MainWindowFinance):
        MainWindowFinance.setObjectName("MainWindowFinance")
        MainWindowFinance.resize(1045, 526)
        MainWindowFinance.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindowFinance)
        self.centralwidget.setStyleSheet("QWidget #centralwidget\n"
"{\n"
"border-image: url(:/background/image 1.png) 0 0 0 0 stretch stretch;\n"
"border-color: rgb(26, 61, 119);\n"
"border: solid 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(-1, 65, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(26, 61, 119);\n"
"                                        ")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_8.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(55, 40, 55, 40)
        self.horizontalLayout_2.setSpacing(55)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonOffres = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOffres.sizePolicy().hasHeightForWidth())
        self.pushButtonOffres.setSizePolicy(sizePolicy)
        self.pushButtonOffres.setMinimumSize(QtCore.QSize(253, 253))
        self.pushButtonOffres.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonOffres.setFont(font)
        self.pushButtonOffres.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonOffres.setStyleSheet("border-radius: 10px;\n"
"                                                    border-top:2px solid;\n"
"                                                    border-color:rgb(26, 61, 119)\n"
"                                                ")
        self.pushButtonOffres.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Offres 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOffres.setIcon(icon)
        self.pushButtonOffres.setIconSize(QtCore.QSize(320, 252))
        self.pushButtonOffres.setCheckable(True)
        self.pushButtonOffres.setObjectName("pushButtonOffres")
        self.horizontalLayout_2.addWidget(self.pushButtonOffres)
        self.pushButtonFacture = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFacture.sizePolicy().hasHeightForWidth())
        self.pushButtonFacture.setSizePolicy(sizePolicy)
        self.pushButtonFacture.setMinimumSize(QtCore.QSize(253, 253))
        self.pushButtonFacture.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonFacture.setFont(font)
        self.pushButtonFacture.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonFacture.setStyleSheet("border-radius: 10px;\n"
"                                                    border-top:2px solid;\n"
"                                                    border-color:rgb(26, 61, 119)\n"
"                                                ")
        self.pushButtonFacture.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Factures 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFacture.setIcon(icon1)
        self.pushButtonFacture.setIconSize(QtCore.QSize(320, 252))
        self.pushButtonFacture.setCheckable(True)
        self.pushButtonFacture.setObjectName("pushButtonFacture")
        self.horizontalLayout_2.addWidget(self.pushButtonFacture)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addWidget(self.widget)
        MainWindowFinance.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowFinance)
        QtCore.QMetaObject.connectSlotsByName(MainWindowFinance)

    def retranslateUi(self, MainWindowFinance):
        _translate = QtCore.QCoreApplication.translate
        MainWindowFinance.setWindowTitle(_translate("MainWindowFinance", "MainWindow"))
        self.label.setText(_translate("MainWindowFinance", "Finance"))
import finance_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowFinance = QtWidgets.QMainWindow()
    ui = Ui_MainWindowFinance()
    ui.setupUi(MainWindowFinance)
    MainWindowFinance.show()
    sys.exit(app.exec_())
