# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuivieAthlete.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSuivieDev(object):
    def setupUi(self, DialogSuivieDev):
        DialogSuivieDev.setObjectName("DialogSuivieDev")
        DialogSuivieDev.resize(643, 465)
        DialogSuivieDev.setStyleSheet("QDialog#DialogSuivieDev{\n"
"    \n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSuivieDev)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(DialogSuivieDev)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel#label{\n"
"    \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(26, 61, 119);\n"
"    \n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.lineEditNom = QtWidgets.QLineEdit(self.widget)
        self.lineEditNom.setMinimumSize(QtCore.QSize(606, 30))
        self.lineEditNom.setReadOnly(True)
        self.lineEditNom.setObjectName("lineEditNom")
        self.verticalLayout_2.addWidget(self.lineEditNom)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.lineEditPrenom = QtWidgets.QLineEdit(self.widget)
        self.lineEditPrenom.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditPrenom.setReadOnly(True)
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.verticalLayout_2.addWidget(self.lineEditPrenom)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.comboBoxSport = QtWidgets.QComboBox(self.widget)
        self.comboBoxSport.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxSport.setStyleSheet("QComboBox#comboBoxSport{\n"
"    \n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.comboBoxSport.setObjectName("comboBoxSport")
        self.comboBoxSport.addItem("")
        self.comboBoxSport.addItem("")
        self.comboBoxSport.addItem("")
        self.comboBoxSport.addItem("")
        self.comboBoxSport.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxSport)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOK = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonOK.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonOK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonOK.setStyleSheet("background-color: rgb(130, 255, 96);")
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.pushButtonAnnuler = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonAnnuler.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonAnnuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAnnuler.setStyleSheet("background-color:rgb(255, 92, 95)")
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.horizontalLayout.addWidget(self.pushButtonAnnuler)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(9, 1)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(DialogSuivieDev)
        QtCore.QMetaObject.connectSlotsByName(DialogSuivieDev)

    def retranslateUi(self, DialogSuivieDev):
        _translate = QtCore.QCoreApplication.translate
        DialogSuivieDev.setWindowTitle(_translate("DialogSuivieDev", "Suivie de développement d\'un athlète"))
        self.label.setText(_translate("DialogSuivieDev", "         Suivie d\'un athlète"))
        self.lineEditNom.setPlaceholderText(_translate("DialogSuivieDev", "Nom"))
        self.lineEditPrenom.setPlaceholderText(_translate("DialogSuivieDev", "Prénom"))
        self.comboBoxSport.setItemText(0, _translate("DialogSuivieDev", "Sport"))
        self.comboBoxSport.setItemText(1, _translate("DialogSuivieDev", "Karate"))
        self.comboBoxSport.setItemText(2, _translate("DialogSuivieDev", "Judo"))
        self.comboBoxSport.setItemText(3, _translate("DialogSuivieDev", "Fitness"))
        self.comboBoxSport.setItemText(4, _translate("DialogSuivieDev", "Kick boxing"))
        self.pushButtonOK.setText(_translate("DialogSuivieDev", "OK"))
        self.pushButtonAnnuler.setText(_translate("DialogSuivieDev", "Annuler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSuivieDev = QtWidgets.QDialog()
    ui = Ui_DialogSuivieDev()
    ui.setupUi(DialogSuivieDev)
    DialogSuivieDev.show()
    sys.exit(app.exec_())
