# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuivieAthleteJudo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSuivieJudo(object):
    def setupUi(self, DialogSuivieJudo):
        DialogSuivieJudo.setObjectName("DialogSuivieJudo")
        DialogSuivieJudo.resize(643, 465)
        DialogSuivieJudo.setStyleSheet("QDialog#DialogSuivieJudo{\n"
"    \n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSuivieJudo)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(DialogSuivieJudo)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel#label{\n"
"    \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(26, 61, 119);\n"
"    \n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.lineEditNom = QtWidgets.QLineEdit(self.widget)
        self.lineEditNom.setMinimumSize(QtCore.QSize(606, 30))
        self.lineEditNom.setReadOnly(True)
        self.lineEditNom.setObjectName("lineEditNom")
        self.verticalLayout_2.addWidget(self.lineEditNom)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.lineEditPrenom = QtWidgets.QLineEdit(self.widget)
        self.lineEditPrenom.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditPrenom.setReadOnly(True)
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.verticalLayout_2.addWidget(self.lineEditPrenom)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.comboBoxCeintureJudo = QtWidgets.QComboBox(self.widget)
        self.comboBoxCeintureJudo.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxCeintureJudo.setStyleSheet("QComboBox#comboBoxCeintureJudo{\n"
"    \n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.comboBoxCeintureJudo.setObjectName("comboBoxCeintureJudo")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.comboBoxCeintureJudo.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxCeintureJudo)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOK = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonOK.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonOK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonOK.setStyleSheet("background-color: rgb(130, 255, 96);")
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.pushButtonAnnuler = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonAnnuler.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonAnnuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAnnuler.setStyleSheet("background-color:rgb(255, 92, 95)")
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.horizontalLayout.addWidget(self.pushButtonAnnuler)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(9, 1)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(DialogSuivieJudo)
        QtCore.QMetaObject.connectSlotsByName(DialogSuivieJudo)

    def retranslateUi(self, DialogSuivieJudo):
        _translate = QtCore.QCoreApplication.translate
        DialogSuivieJudo.setWindowTitle(_translate("DialogSuivieJudo", "Suivie de développement d\'un athlète"))
        self.label.setText(_translate("DialogSuivieJudo", "         Suivie d\'un athlète"))
        self.lineEditNom.setPlaceholderText(_translate("DialogSuivieJudo", "Nom"))
        self.lineEditPrenom.setPlaceholderText(_translate("DialogSuivieJudo", "Prénom"))
        self.comboBoxCeintureJudo.setItemText(0, _translate("DialogSuivieJudo", "Ceinture"))
        self.comboBoxCeintureJudo.setItemText(1, _translate("DialogSuivieJudo", "Blanche"))
        self.comboBoxCeintureJudo.setItemText(2, _translate("DialogSuivieJudo", "Blanche-jaune"))
        self.comboBoxCeintureJudo.setItemText(3, _translate("DialogSuivieJudo", "Jaune"))
        self.comboBoxCeintureJudo.setItemText(4, _translate("DialogSuivieJudo", "Jaune-rouge"))
        self.comboBoxCeintureJudo.setItemText(5, _translate("DialogSuivieJudo", "Orange"))
        self.comboBoxCeintureJudo.setItemText(6, _translate("DialogSuivieJudo", "Orange-verte"))
        self.comboBoxCeintureJudo.setItemText(7, _translate("DialogSuivieJudo", "Verte"))
        self.comboBoxCeintureJudo.setItemText(8, _translate("DialogSuivieJudo", "Bleue"))
        self.comboBoxCeintureJudo.setItemText(9, _translate("DialogSuivieJudo", "Marron"))
        self.pushButtonOK.setText(_translate("DialogSuivieJudo", "OK"))
        self.pushButtonAnnuler.setText(_translate("DialogSuivieJudo", "Annuler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSuivieJudo = QtWidgets.QDialog()
    ui = Ui_DialogSuivieJudo()
    ui.setupUi(DialogSuivieJudo)
    DialogSuivieJudo.show()
    sys.exit(app.exec_())
