# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EDT(object):
    def setupUi(self, EDT):
        EDT.setObjectName("EDT")
        EDT.resize(883, 559)
        EDT.setStyleSheet("background-color: rgb(210, 210, 210);")
        self.verticalLayout = QtWidgets.QVBoxLayout(EDT)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(EDT)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(26, 61, 119);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(EDT)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(1000, -1, 5, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.modifier = QtWidgets.QPushButton(self.widget_3)
        self.modifier.setMinimumSize(QtCore.QSize(50, 50))
        self.modifier.setMaximumSize(QtCore.QSize(50, 50))
        self.modifier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.modifier.setStyleSheet("background-color: rgb(26, 61, 119);\n"
"border-radius:5px")
        self.modifier.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/add (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.modifier.setIcon(icon)
        self.modifier.setIconSize(QtCore.QSize(35, 35))
        self.modifier.setCheckable(True)
        self.modifier.setObjectName("modifier")
        self.gridLayout.addWidget(self.modifier, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(EDT)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setStyleSheet("QHeaderView::section {background-color: rgb(210, 210, 210);\n"
"border: 1px solid rgb(26, 61, 119);\n"
"font-size: 12pt;\n"
"font:bold;}\n"
"QTableView {\n"
"border: 2px solid rgb(26, 61, 119);\n"
"border-top:1px solid rgb(26, 61, 119);\n"
"background-color: rgb(210, 210, 210);\n"
"}\n"
"QHeaderView {background-color: rgb(210, 210, 210);}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(106)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(EDT)
        QtCore.QMetaObject.connectSlotsByName(EDT)

    def retranslateUi(self, EDT):
        _translate = QtCore.QCoreApplication.translate
        EDT.setWindowTitle(_translate("EDT", "EDT"))
        self.label.setText(_translate("EDT", "EMPLOI DU TEMPS"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("EDT", "Temps"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("EDT", "Dimanche"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("EDT", "Lundi"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("EDT", "Mardi"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("EDT", "Mercredi"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("EDT", "Jeudi"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("EDT", "Vendredi"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("EDT", "Samedi"))
        EDT.showMaximized()
from emploiDuTemps import edt_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EDT = QtWidgets.QWidget()
    ui = Ui_EDT()
    ui.setupUi(EDT)
    EDT.show()
    sys.exit(app.exec_())
