# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup(object):
    def setupUi(self, signup):
        signup.setObjectName("signup")
        signup.resize(910, 540)
        signup.setMinimumSize(QtCore.QSize(1200, 800))
        signup.setMaximumSize(QtCore.QSize(1200, 800))
        signup.setStyleSheet("QWidget #signup\n"
"{\n"
"background-color: rgb(217, 217, 217)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(signup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background = QtWidgets.QWidget(signup)
        self.background.setStyleSheet("QWidget #background{\n"
"border-image: url(:/background/image 1.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.background.setObjectName("background")
        self.gridLayout = QtWidgets.QGridLayout(self.background)
        self.gridLayout.setObjectName("gridLayout")
        self.box = QtWidgets.QWidget(self.background)
        self.box.setMinimumSize(QtCore.QSize(400, 300))
        self.box.setMaximumSize(QtCore.QSize(400, 350))
        self.box.setStyleSheet("QWidget #box{\n"
"background-color: rgb(248, 248, 248);\n"
"border-radius:15px;\n"
"}")
        self.box.setObjectName("box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inscriptionconnexion = QtWidgets.QLabel(self.box)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.inscriptionconnexion.setFont(font)
        self.inscriptionconnexion.setStyleSheet("color: rgb(26, 61, 119);")
        self.inscriptionconnexion.setAlignment(QtCore.Qt.AlignCenter)
        self.inscriptionconnexion.setObjectName("inscriptionconnexion")
        self.verticalLayout_2.addWidget(self.inscriptionconnexion)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.voulezvous = QtWidgets.QLabel(self.box)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.voulezvous.setFont(font)
        self.voulezvous.setStyleSheet("color: rgb(127, 126, 131,60%);")
        self.voulezvous.setAlignment(QtCore.Qt.AlignCenter)
        self.voulezvous.setIndent(6)
        self.voulezvous.setObjectName("voulezvous")
        self.verticalLayout_2.addWidget(self.voulezvous)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.box)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"border: 0;\n"
"border-radius:7px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.box)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"border: 0;\n"
"border-radius:7px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.lineEdit = QtWidgets.QLineEdit(self.box)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"border: 0;\n"
"border-radius:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.box)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"border: 0;\n"
"border-radius:7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.seconnecter = QtWidgets.QPushButton(self.box)
        self.seconnecter.setMinimumSize(QtCore.QSize(0, 30))
        self.seconnecter.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.seconnecter.setFont(font)
        self.seconnecter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seconnecter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(26, 61, 119);\n"
"border-radius:7px")
        self.seconnecter.setCheckable(True)
        self.seconnecter.setObjectName("seconnecter")
        self.verticalLayout_2.addWidget(self.seconnecter)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.gridLayout.addWidget(self.box, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.background)

        self.retranslateUi(signup)
        QtCore.QMetaObject.connectSlotsByName(signup)

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "Form"))
        self.inscriptionconnexion.setText(_translate("signup", "Inscrivez-Vous"))
        self.voulezvous.setText(_translate("signup", "Inscrivez-vous pour creer votre propre espace"))
        self.lineEdit_4.setPlaceholderText(_translate("signup", "  Nom d\'Utilisateur"))
        self.lineEdit_3.setPlaceholderText(_translate("signup", " Adresse Mail"))
        self.lineEdit.setPlaceholderText(_translate("signup", " Mot de Passe"))
        self.lineEdit_2.setPlaceholderText(_translate("signup", " Confirmer le Mot de Passe"))
        self.seconnecter.setText(_translate("signup", "S\'inscrire"))
import signup_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signup = QtWidgets.QWidget()
    ui = Ui_signup()
    ui.setupUi(signup)
    signup.show()
    sys.exit(app.exec_())
