# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowGest(object):
    def setupUi(self, MainWindowGest):
        MainWindowGest.setObjectName("MainWindowGest")
        MainWindowGest.resize(1243, 443)
        self.centralwidget = QtWidgets.QWidget(MainWindowGest)
        self.centralwidget.setStyleSheet("QWidget #centralwidget\n"
"{\n"
"border-image: url(:/hhh/image 1.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("QWidget #widget_2\n"
"{\n"
"border-top: 2px solid ;\n"
"                                border-left: 2px solid;\n"
"                                border-right: 2px solid ;\n"
"                                border-color: rgb(26, 61, 119);\n"
"          }                  ")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(-1, 40, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(26, 61, 119);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_8.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("border-bottom: 2px solid;\n"
"                                border-left: 2px solid;\n"
"                                border-right: 2px solid;\n"
"                                border-color:rgb(26, 61, 119);\n"
"                            ")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(45, -1, 45, -1)
        self.horizontalLayout_2.setSpacing(45)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonMembres = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMembres.sizePolicy().hasHeightForWidth())
        self.pushButtonMembres.setSizePolicy(sizePolicy)
        self.pushButtonMembres.setMinimumSize(QtCore.QSize(250, 250))
        self.pushButtonMembres.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonMembres.setFont(font)
        self.pushButtonMembres.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMembres.setStyleSheet("")
        self.pushButtonMembres.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/hhh/membres.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMembres.setIcon(icon)
        self.pushButtonMembres.setIconSize(QtCore.QSize(320, 250))
        self.pushButtonMembres.setCheckable(True)
        self.pushButtonMembres.setObjectName("pushButtonMembres")
        self.horizontalLayout_2.addWidget(self.pushButtonMembres)
        self.pushButtonAbonnements = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAbonnements.sizePolicy().hasHeightForWidth())
        self.pushButtonAbonnements.setSizePolicy(sizePolicy)
        self.pushButtonAbonnements.setMinimumSize(QtCore.QSize(250, 250))
        self.pushButtonAbonnements.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonAbonnements.setFont(font)
        self.pushButtonAbonnements.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAbonnements.setStyleSheet("")
        self.pushButtonAbonnements.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/hhh/Abonnements.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAbonnements.setIcon(icon1)
        self.pushButtonAbonnements.setIconSize(QtCore.QSize(320, 250))
        self.pushButtonAbonnements.setCheckable(True)
        self.pushButtonAbonnements.setObjectName("pushButtonAbonnements")
        self.horizontalLayout_2.addWidget(self.pushButtonAbonnements)
        self.pushButtonEdt = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEdt.sizePolicy().hasHeightForWidth())
        self.pushButtonEdt.setSizePolicy(sizePolicy)
        self.pushButtonEdt.setMinimumSize(QtCore.QSize(250, 250))
        self.pushButtonEdt.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonEdt.setFont(font)
        self.pushButtonEdt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonEdt.setStyleSheet("")
        self.pushButtonEdt.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hhh/EDT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEdt.setIcon(icon2)
        self.pushButtonEdt.setIconSize(QtCore.QSize(320, 250))
        self.pushButtonEdt.setCheckable(True)
        self.pushButtonEdt.setObjectName("pushButtonEdt")
        self.horizontalLayout_2.addWidget(self.pushButtonEdt)
        self.pushButtonLosts = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLosts.sizePolicy().hasHeightForWidth())
        self.pushButtonLosts.setSizePolicy(sizePolicy)
        self.pushButtonLosts.setMinimumSize(QtCore.QSize(250, 250))
        self.pushButtonLosts.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonLosts.setFont(font)
        self.pushButtonLosts.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonLosts.setStyleSheet("")
        self.pushButtonLosts.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/hhh/losts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLosts.setIcon(icon3)
        self.pushButtonLosts.setIconSize(QtCore.QSize(320, 250))
        self.pushButtonLosts.setCheckable(True)
        self.pushButtonLosts.setObjectName("pushButtonLosts")
        self.horizontalLayout_2.addWidget(self.pushButtonLosts)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addWidget(self.widget)
        MainWindowGest.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowGest)
        QtCore.QMetaObject.connectSlotsByName(MainWindowGest)

    def retranslateUi(self, MainWindowGest):
        _translate = QtCore.QCoreApplication.translate
        MainWindowGest.setWindowTitle(_translate("MainWindowGest", "MainWindow"))
        self.label.setText(_translate("MainWindowGest", "JSS Excellence de Saoula."))
import resources_main_gest


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowGest = QtWidgets.QMainWindow()
    ui = Ui_MainWindowGest()
    ui.setupUi(MainWindowGest)
    MainWindowGest.show()
    sys.exit(app.exec_())
