# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajouterObjet.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from connexion_DB import connect_to_DB

class Ui_Dialog(object):
    def __init__(self, main_window):
        self.main_window = main_window
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 580)
        Dialog.setMinimumSize(QtCore.QSize(650, 580))
        Dialog.setMaximumSize(QtCore.QSize(650, 580))
        Dialog.setStyleSheet("QDialog#Dialog{\n"
"background-color: rgb(240, 240, 240);}")
        self.lineEditDescription = QtWidgets.QLineEdit(Dialog)
        self.lineEditDescription.setGeometry(QtCore.QRect(20, 240, 611, 281))
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 491, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditObjet = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditObjet.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditObjet.setObjectName("lineEditObjet")
        self.horizontalLayout.addWidget(self.lineEditObjet)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 10)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 100, 491, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditLieu = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditLieu.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditLieu.setObjectName("lineEditLieu")
        self.horizontalLayout_2.addWidget(self.lineEditLieu)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 10)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 170, 201, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget2)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_3.addWidget(self.dateEdit)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(510, 530, 121, 31))
        self.pushButton.setStyleSheet("background-color: rgb(0, 189, 0);\n"
"color: rgb(252, 252, 252);\n"
"border-radius:5px;")
        self.pushButton.setObjectName("pushButton")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.add_object)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEditDescription.setPlaceholderText(_translate("Dialog", "Description..."))
        self.label.setText(_translate("Dialog", "Objet"))
        self.label_2.setText(_translate("Dialog", "Lieu"))
        self.label_3.setText(_translate("Dialog", "Date"))
        self.pushButton.setText(_translate("Dialog", "OK"))

    def add_object(self):
        object_name = self.lineEditObjet.text()
        Lieu = self.lineEditLieu.text()
        date = self.dateEdit.date().toString("yyyy-MM-dd")
        description = self.lineEditDescription.text()
        if object_name == "" or Lieu == "" or description == "":
            self.msg = QtWidgets.QMessageBox()
            self.msg.setIcon(QtWidgets.QMessageBox.Critical)
            self.msg.setText("Veuillez Saisir Les Champs Obligatoires")
            self.msg.setWindowTitle("Erreur")
            self.msg.exec_()
        elif self.insertDb(object_name, date, Lieu, description):
            self.msg = QtWidgets.QMessageBox()
            self.msg.setIcon(QtWidgets.QMessageBox.Information)
            self.msg.setText("Objet Ajouté avec succès")
            self.msg.setWindowTitle("Succès")
            self.msg.exec_()
            self.main_window.update_object_list()
            self.lineEditObjet.setText("")
            self.lineEditLieu.setText("")
            self.dateEdit.setDate(QtCore.QDate.currentDate())
            self.lineEditDescription.setText("")
        else:
                self.msg = QtWidgets.QMessageBox()
                self.msg.setIcon(QtWidgets.QMessageBox.Critical)
                self.msg.setText("Insertion Echouée")
                self.msg.setWindowTitle("Erreur")
                self.msg.exec_()

    def insertDb(self, object_name, date, Lieu, description):
        connection, cursor = connect_to_DB()
        query = "INSERT INTO objets(object_name,datee,lieu,description) VALUES (%s, %s, %s, %s)"
        values = (object_name, date, Lieu, description)
        cursor.execute(query, values)
        connection.commit()
        cursor.close()
        return True



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())