# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'objetsPerdues.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
<<<<<<< HEAD
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QMessageBox, QTextEdit , QLabel, QComboBox, QLineEdit
import mysql.connector
=======
>>>>>>> 10e8a07f3486aa57f17bd31c357ccf2368c6415a


class Ui_MainWindowObjetsPerdues(object):
    def setupUi(self, MainWindowObjetsPerdues):
        MainWindowObjetsPerdues.setObjectName("MainWindowObjetsPerdues")
<<<<<<< HEAD
        MainWindowObjetsPerdues.resize(1327, 576)
=======
        MainWindowObjetsPerdues.resize(933, 632)
>>>>>>> 10e8a07f3486aa57f17bd31c357ccf2368c6415a
        MainWindowObjetsPerdues.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindowObjetsPerdues)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditRecherche = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRecherche.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditRecherche.setObjectName("lineEditRecherche")
        self.horizontalLayout.addWidget(self.lineEditRecherche)
        self.pushButtonRechercher = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRechercher.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonRechercher.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonRechercher.setStyleSheet("background-color: rgb(35, 84, 209);\n"
"color: rgb(252, 252, 252);\n"
"border-radius:5px;\n"
"")
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.horizontalLayout.addWidget(self.pushButtonRechercher)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonAjourter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAjourter.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonAjourter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAjourter.setStyleSheet("background-color: rgb(0, 189, 0);\n"
"color: rgb(252, 252, 252);\n"
"border-radius:5px;\n"
"")
        self.pushButtonAjourter.setObjectName("pushButtonAjourter")
        self.horizontalLayout.addWidget(self.pushButtonAjourter)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSupprimer.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonSupprimer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonSupprimer.setStyleSheet("background-color: rgb(255, 93, 93);\n"
"border-radius:5px;\n"
"color: rgb(252, 252, 252);")
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.horizontalLayout.addWidget(self.pushButtonSupprimer)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(6, 1)
        self.horizontalLayout.setStretch(7, 1)
        self.horizontalLayout.setStretch(8, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidgetLostObjects = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetLostObjects.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetLostObjects.setColumnCount(4)
        self.tableWidgetLostObjects.setObjectName("tableWidgetLostObjects")
        self.tableWidgetLostObjects.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLostObjects.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLostObjects.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLostObjects.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetLostObjects.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidgetLostObjects)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindowObjetsPerdues.setCentralWidget(self.centralwidget)
<<<<<<< HEAD
        self.retranslateUi(MainWindowObjetsPerdues)
        QtCore.QMetaObject.connectSlotsByName(MainWindowObjetsPerdues)
        MainWindowObjetsPerdues.showMaximized()
        self.pushButtonRechercher.clicked.connect(self.rechercher_objets)
        self.radioButton.clicked.connect(self.trier_AZ)
        self.radioButton_2.clicked.connect(self.trier_plus_recent)
        self.radioButton_3.clicked.connect(self.trier_plus_ancien)
        self.connection = mysql.connector.connect(
            host="localhost",
            user="oussama",
            password="projet2cp",
            database="projet2cp",
            port="3306"
        )
        self.cursor = self.connection.cursor()
        self.afficher_tout()

        self.tableWidgetLostObjects.setColumnWidth(0, 200)
        self.tableWidgetLostObjects.setColumnWidth(1, 150)
        self.tableWidgetLostObjects.setColumnWidth(2, 200)
        self.tableWidgetLostObjects.setColumnWidth(3, 1500)
    def retranslateUi(self, MainWindowObjetsPerdues):
        _translate = QtCore.QCoreApplication.translate
        MainWindowObjetsPerdues.setWindowTitle(_translate("MainWindowObjetsPerdues", "Objets perdus"))
        self.lineEditRecherche.setPlaceholderText(_translate("MainWindowObjetsPerdues", "Rechercher un objet"))
=======

        self.retranslateUi(MainWindowObjetsPerdues)
        QtCore.QMetaObject.connectSlotsByName(MainWindowObjetsPerdues)

        #show window maximiased
        MainWindowObjetsPerdues.showMaximized()
    def retranslateUi(self, MainWindowObjetsPerdues):
        _translate = QtCore.QCoreApplication.translate
        MainWindowObjetsPerdues.setWindowTitle(_translate("MainWindowObjetsPerdues", "Objets perdues"))
        self.lineEditRecherche.setPlaceholderText(_translate("MainWindowObjetsPerdues", "Rechercher un onbejt"))
>>>>>>> 10e8a07f3486aa57f17bd31c357ccf2368c6415a
        self.pushButtonRechercher.setText(_translate("MainWindowObjetsPerdues", "Rechercher"))
        self.radioButton.setText(_translate("MainWindowObjetsPerdues", "A-Z"))
        self.radioButton_2.setText(_translate("MainWindowObjetsPerdues", "Plus récent"))
        self.radioButton_3.setText(_translate("MainWindowObjetsPerdues", "Plus ancien"))
        self.pushButtonAjourter.setText(_translate("MainWindowObjetsPerdues", "Ajouter"))
        self.pushButtonSupprimer.setText(_translate("MainWindowObjetsPerdues", "Supprimer"))
        self.tableWidgetLostObjects.setSortingEnabled(True)
        item = self.tableWidgetLostObjects.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowObjetsPerdues", "Objet"))
        item = self.tableWidgetLostObjects.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowObjetsPerdues", "Date"))
        item = self.tableWidgetLostObjects.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowObjetsPerdues", "Lieu"))
        item = self.tableWidgetLostObjects.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowObjetsPerdues", "Description"))
<<<<<<< HEAD
    def afficher_tout(self):
        query = "SELECT object_name, datee, lieu, description FROM objets"
        self.cursor.execute(query)
        data = self.cursor.fetchall()
        self.tableWidgetLostObjects.setRowCount(len(data))
        for numero_ligne, donnees_ligne in enumerate(data):
            for numero_colonne, donnee_colonne in enumerate(donnees_ligne):
                item = QtWidgets.QTableWidgetItem(str(donnee_colonne))
                item.setFont(QtGui.QFont("Arial", 10))
                self.tableWidgetLostObjects.setItem(numero_ligne, numero_colonne, item)
        self.tableWidgetLostObjects.resizeColumnsToContents()

    def rechercher_objets(self):
        name_objet = self.lineEditRecherche.text()
        query = "SELECT object_name, datee, lieu, description FROM objets WHERE object_name LIKE %s"
        self.cursor.execute(query, (name_objet,))
        data = self.cursor.fetchall()
        if not data:
            self.msg = QtWidgets.QMessageBox()
            self.msg.setIcon(QtWidgets.QMessageBox.Information)
            self.msg.setText("Aucun objet n'existe avec ce nom.")
            self.msg.setWindowTitle("Erreur")
            self.msg.exec_()
            self.lineEditRecherche.setText("")
            return
        self.tableWidgetLostObjects.clearContents()
        self.tableWidgetLostObjects.setRowCount(0)
        for numero_ligne, donnees_ligne in enumerate(data):
            self.tableWidgetLostObjects.insertRow(numero_ligne)
            for numero_colonne, donnee_colonne in enumerate(donnees_ligne):
                item = QtWidgets.QTableWidgetItem(str(donnee_colonne))
                item.setFont(QtGui.QFont("Arial", 10))
                self.tableWidgetLostObjects.setItem(numero_ligne, numero_colonne, item)


    def trier_AZ(self):
        self.tableWidgetLostObjects.sortByColumn(0, QtCore.Qt.AscendingOrder)
    def trier_plus_recent(self):
        self.tableWidgetLostObjects.sortByColumn(1, QtCore.Qt.DescendingOrder)
    def trier_plus_ancien(self):
        self.tableWidgetLostObjects.sortByColumn(1, QtCore.Qt.AscendingOrder)
=======
>>>>>>> 10e8a07f3486aa57f17bd31c357ccf2368c6415a


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowObjetsPerdues = QtWidgets.QMainWindow()
    ui = Ui_MainWindowObjetsPerdues()
    ui.setupUi(MainWindowObjetsPerdues)
    MainWindowObjetsPerdues.show()
    sys.exit(app.exec_())
