# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuivieAthleteKarate.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from connexion_DB import connect_to_DB


class Ui_DialogSuivieKarate(object):
    def setupUi(self, DialogSuivieKarate):
        DialogSuivieKarate.setObjectName("DialogSuivieKarate")
        DialogSuivieKarate.resize(643, 458)
        DialogSuivieKarate.setStyleSheet("QDialog#DialogSuivieKarate\n"
"{\n"
"    \n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSuivieKarate)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(DialogSuivieKarate)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel#label{\n"
"    \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(26, 61, 119);\n"
"    \n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.lineEditNom = QtWidgets.QLineEdit(self.widget)
        self.lineEditNom.setMinimumSize(QtCore.QSize(606, 30))
        self.lineEditNom.setReadOnly(True)
        self.lineEditNom.setObjectName("lineEditNom")
        self.verticalLayout_2.addWidget(self.lineEditNom)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.lineEditPrenom = QtWidgets.QLineEdit(self.widget)
        self.lineEditPrenom.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditPrenom.setReadOnly(True)
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.verticalLayout_2.addWidget(self.lineEditPrenom)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.comboBoxCeintureKarate = QtWidgets.QComboBox(self.widget)
        self.comboBoxCeintureKarate.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxCeintureKarate.setStyleSheet("QComboBox#comboBoxCeintureKarate{\n"
"    \n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.comboBoxCeintureKarate.setObjectName("comboBoxCeintureKarate")
        self.comboBoxCeintureKarate.addItem("")
        self.comboBoxCeintureKarate.addItem("")
        self.comboBoxCeintureKarate.addItem("")
        self.comboBoxCeintureKarate.addItem("")
        self.comboBoxCeintureKarate.addItem("")
        self.comboBoxCeintureKarate.addItem("")
        self.comboBoxCeintureKarate.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxCeintureKarate)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOK = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonOK.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonOK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonOK.setStyleSheet("background-color: rgb(130, 255, 96);")
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.pushButtonAnnuler = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonAnnuler.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonAnnuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAnnuler.setStyleSheet("background-color:rgb(255, 92, 95)")
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.horizontalLayout.addWidget(self.pushButtonAnnuler)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(9, 1)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(DialogSuivieKarate)
        QtCore.QMetaObject.connectSlotsByName(DialogSuivieKarate)
        self.pushButtonOK.clicked.connect(self.modifier_ceinture)

    def retranslateUi(self, DialogSuivieKarate):
        _translate = QtCore.QCoreApplication.translate
        DialogSuivieKarate.setWindowTitle(_translate("DialogSuivieKarate", "Suivie de développement d\'un athlète"))
        self.label.setText(_translate("DialogSuivieKarate", "         Suivie d\'un athlète"))
        self.lineEditNom.setPlaceholderText(_translate("DialogSuivieKarate", "Nom"))
        self.lineEditPrenom.setPlaceholderText(_translate("DialogSuivieKarate", "Prénom"))
        self.comboBoxCeintureKarate.setItemText(0, _translate("DialogSuivieKarate", "Ceinture"))
        self.comboBoxCeintureKarate.setItemText(1, _translate("DialogSuivieKarate", "Blanche"))
        self.comboBoxCeintureKarate.setItemText(2, _translate("DialogSuivieKarate", "Jaune"))
        self.comboBoxCeintureKarate.setItemText(3, _translate("DialogSuivieKarate", "Orange"))
        self.comboBoxCeintureKarate.setItemText(4, _translate("DialogSuivieKarate", "Verte"))
        self.comboBoxCeintureKarate.setItemText(5, _translate("DialogSuivieKarate", "Bleue"))
        self.comboBoxCeintureKarate.setItemText(6, _translate("DialogSuivieKarate", "Marron"))
        self.pushButtonOK.setText(_translate("DialogSuivieKarate", "OK"))
        self.pushButtonAnnuler.setText(_translate("DialogSuivieKarate", "Annuler"))

    def modifier_ceinture(self):
        ceinture = self.comboBoxCeintureKarate.currentText()
        nom = self.lineEditNom.text().strip()
        prénom = self.lineEditPrenom.text().strip()
        if ceinture == "Ceinture":
            self.msg = QtWidgets.QMessageBox()
            self.msg.setIcon(QtWidgets.QMessageBox.Information)
            self.msg.setText("Veuillez choisir une ceinture.")
            self.msg.setWindowTitle("Erreur")
            self.msg.exec_()
            return
        try:
            connection, cursor = connect_to_DB()
            query = "UPDATE adhérant SET ceinture = %s WHERE nom = %s AND prénom = %s"
            values = (ceinture, nom, prénom)
            cursor.execute(query, values)
            connection.commit()
            self.msg = QtWidgets.QMessageBox()
            self.msg.setIcon(QtWidgets.QMessageBox.Information)
            self.msg.setText("Ceinture mise à jour avec succès.")
            self.msg.setWindowTitle("Succès")
            self.msg.exec_()

        except Exception as e:
            self.msg = QtWidgets.QMessageBox()
            self.msg.setIcon(QtWidgets.QMessageBox.Critical)
            self.msg.setText(f"Erreur lors de la mise à jour: {str(e)}")
            self.msg.setWindowTitle("Erreur")
            self.msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSuivieKarate = QtWidgets.QDialog()
    ui = Ui_DialogSuivieKarate()
    ui.setupUi(DialogSuivieKarate)
    DialogSuivieKarate.show()
    sys.exit(app.exec_())
