# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuivieAthleteKick.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSuivieKickBoxing(object):
    def setupUi(self, DialogSuivieKickBoxing):
        DialogSuivieKickBoxing.setObjectName("DialogSuivieKickBoxing")
        DialogSuivieKickBoxing.resize(643, 458)
        DialogSuivieKickBoxing.setStyleSheet("QDialog#DialogSuivieKickBoxing\n"
"{\n"
"    \n"
"    background-color: rgb(210, 210, 210);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSuivieKickBoxing)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(DialogSuivieKickBoxing)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel#label{\n"
"    \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(26, 61, 119);\n"
"    \n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.lineEditNom = QtWidgets.QLineEdit(self.widget)
        self.lineEditNom.setMinimumSize(QtCore.QSize(606, 30))
        self.lineEditNom.setReadOnly(True)
        self.lineEditNom.setObjectName("lineEditNom")
        self.verticalLayout_2.addWidget(self.lineEditNom)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.lineEditPrenom = QtWidgets.QLineEdit(self.widget)
        self.lineEditPrenom.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditPrenom.setReadOnly(True)
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.verticalLayout_2.addWidget(self.lineEditPrenom)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.comboBoxPoidsKick = QtWidgets.QComboBox(self.widget)
        self.comboBoxPoidsKick.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBoxPoidsKick.setStyleSheet("QComboBox#comboBoxPoidsKick{\n"
"    \n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}")
        self.comboBoxPoidsKick.setObjectName("comboBoxPoidsKick")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.comboBoxPoidsKick.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxPoidsKick)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOK = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonOK.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonOK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonOK.setStyleSheet("background-color: rgb(130, 255, 96);")
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.pushButtonAnnuler = QtWidgets.QPushButton(self.widget_2)
        self.pushButtonAnnuler.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonAnnuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAnnuler.setStyleSheet("background-color:rgb(255, 92, 95)")
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.horizontalLayout.addWidget(self.pushButtonAnnuler)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(9, 1)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(DialogSuivieKickBoxing)
        QtCore.QMetaObject.connectSlotsByName(DialogSuivieKickBoxing)

    def retranslateUi(self, DialogSuivieKickBoxing):
        _translate = QtCore.QCoreApplication.translate
        DialogSuivieKickBoxing.setWindowTitle(_translate("DialogSuivieKickBoxing", "Suivie de développement d\'un athlète"))
        self.label.setText(_translate("DialogSuivieKickBoxing", "         Suivie d\'un athlète"))
        self.lineEditNom.setPlaceholderText(_translate("DialogSuivieKickBoxing", "Nom"))
        self.lineEditPrenom.setPlaceholderText(_translate("DialogSuivieKickBoxing", "Prénom"))
        self.comboBoxPoidsKick.setItemText(0, _translate("DialogSuivieKickBoxing", "Poids"))
        self.comboBoxPoidsKick.setItemText(1, _translate("DialogSuivieKickBoxing", "Moustique (Moins de 24kg)"))
        self.comboBoxPoidsKick.setItemText(2, _translate("DialogSuivieKickBoxing", "Pré-mini-mouche (24 à 27 kg)"))
        self.comboBoxPoidsKick.setItemText(3, _translate("DialogSuivieKickBoxing", "Pré-mini-coq (27 à 30 kg)"))
        self.comboBoxPoidsKick.setItemText(4, _translate("DialogSuivieKickBoxing", "Pré-mini-plume (30 à 33 kg)"))
        self.comboBoxPoidsKick.setItemText(5, _translate("DialogSuivieKickBoxing", "Pré-mini-léger (33 à 36 kg)"))
        self.comboBoxPoidsKick.setItemText(6, _translate("DialogSuivieKickBoxing", "Mini-mouche (36 à 39 kg)"))
        self.comboBoxPoidsKick.setItemText(7, _translate("DialogSuivieKickBoxing", "Mini-coq (39 à 42 kg)"))
        self.comboBoxPoidsKick.setItemText(8, _translate("DialogSuivieKickBoxing", "Mini-plume (42 à 45 kg)"))
        self.comboBoxPoidsKick.setItemText(9, _translate("DialogSuivieKickBoxing", "Mini-léger (45 à 48 kg)"))
        self.comboBoxPoidsKick.setItemText(10, _translate("DialogSuivieKickBoxing", "Mouche (48 à 51 kg)"))
        self.comboBoxPoidsKick.setItemText(11, _translate("DialogSuivieKickBoxing", "Coq (51 à 54 kg)"))
        self.comboBoxPoidsKick.setItemText(12, _translate("DialogSuivieKickBoxing", "Plume (54 à 57 kg)"))
        self.comboBoxPoidsKick.setItemText(13, _translate("DialogSuivieKickBoxing", "Super-plume (57 à 60 kg)"))
        self.comboBoxPoidsKick.setItemText(14, _translate("DialogSuivieKickBoxing", "Léger (60 à 63 kg)"))
        self.comboBoxPoidsKick.setItemText(15, _translate("DialogSuivieKickBoxing", "Super-léger (63 à 66 kg)"))
        self.comboBoxPoidsKick.setItemText(16, _translate("DialogSuivieKickBoxing", "Mi-moyen (66 à 70 kg)"))
        self.comboBoxPoidsKick.setItemText(17, _translate("DialogSuivieKickBoxing", "Super-mi-moyen (70 à 74 kg)"))
        self.comboBoxPoidsKick.setItemText(18, _translate("DialogSuivieKickBoxing", "Moyens (74 à 79 kg)"))
        self.comboBoxPoidsKick.setItemText(19, _translate("DialogSuivieKickBoxing", "Mi-lourd (79 à 85 kg)"))
        self.comboBoxPoidsKick.setItemText(20, _translate("DialogSuivieKickBoxing", "Lourd au-delà de 85 kg"))
        self.pushButtonOK.setText(_translate("DialogSuivieKickBoxing", "OK"))
        self.pushButtonAnnuler.setText(_translate("DialogSuivieKickBoxing", "Annuler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSuivieKickBoxing = QtWidgets.QDialog()
    ui = Ui_DialogSuivieKickBoxing()
    ui.setupUi(DialogSuivieKickBoxing)
    DialogSuivieKickBoxing.show()
    sys.exit(app.exec_())
