# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suiviePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QWdidgetSuivie(object):
    def setupUi(self, QWdidgetSuivie):
        QWdidgetSuivie.setObjectName("QWdidgetSuivie")
        QWdidgetSuivie.resize(1373, 605)
        QWdidgetSuivie.setStyleSheet("background-color: rgb(210, 210, 210);")
        self.gridLayout = QtWidgets.QGridLayout(QWdidgetSuivie)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.topheader = QtWidgets.QWidget(QWdidgetSuivie)
        self.topheader.setStyleSheet("\n"
"background-color:  rgb(210, 210, 210)")
        self.topheader.setObjectName("topheader")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.topheader)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.topheader)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(26, 61, 119);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout.addWidget(self.topheader, 0, 0, 1, 1)
        self.table = QtWidgets.QWidget(QWdidgetSuivie)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table.setFont(font)
        self.table.setStyleSheet("\n"
"background-color:  rgb(210, 210, 210)")
        self.table.setObjectName("table")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.table)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.table)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView::section {background-color: rgb(210, 210, 210);\n"
"border: 1px solid rgb(26, 61, 119);\n"
"font-size: 12pt;\n"
"font:bold;}\n"
"QTableView {\n"
"border: 2px solid rgb(26, 61, 119);\n"
"border-top:1px solid rgb(26, 61, 119);\n"
"}\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(5)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(191)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout.addWidget(self.table, 2, 0, 1, 1)
        self.QWidgetNavBar = QtWidgets.QWidget(QWdidgetSuivie)
        self.QWidgetNavBar.setMinimumSize(QtCore.QSize(0, 0))
        self.QWidgetNavBar.setMaximumSize(QtCore.QSize(16777215, 60))
        self.QWidgetNavBar.setStyleSheet("\n"
"background-color:  rgb(210, 210, 210)")
        self.QWidgetNavBar.setObjectName("QWidgetNavBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.QWidgetNavBar)
        self.horizontalLayout.setContentsMargins(20, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEditNom = QtWidgets.QLineEdit(self.QWidgetNavBar)
        self.lineEditNom.setMinimumSize(QtCore.QSize(500, 30))
        self.lineEditNom.setMaximumSize(QtCore.QSize(700, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditNom.setFont(font)
        self.lineEditNom.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(163, 163, 163);\n"
"border-radius:2px")
        self.lineEditNom.setObjectName("lineEditNom")
        self.horizontalLayout.addWidget(self.lineEditNom)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.LineEditPrenom = QtWidgets.QLineEdit(self.QWidgetNavBar)
        self.LineEditPrenom.setMinimumSize(QtCore.QSize(500, 30))
        self.LineEditPrenom.setMaximumSize(QtCore.QSize(700, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LineEditPrenom.setFont(font)
        self.LineEditPrenom.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.LineEditPrenom.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"color: rgb(163, 163, 163);\n"
"border-radius:2px")
        self.LineEditPrenom.setInputMask("")
        self.LineEditPrenom.setText("")
        self.LineEditPrenom.setDragEnabled(False)
        self.LineEditPrenom.setReadOnly(False)
        self.LineEditPrenom.setClearButtonEnabled(False)
        self.LineEditPrenom.setObjectName("LineEditPrenom")
        self.horizontalLayout.addWidget(self.LineEditPrenom)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonRechercher = QtWidgets.QPushButton(self.QWidgetNavBar)
        self.pushButtonRechercher.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonRechercher.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonRechercher.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonRechercher.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border-radius:10px;\n"
"border:1px solid rgb(26, 61, 119);")
        self.pushButtonRechercher.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/loupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRechercher.setIcon(icon)
        self.pushButtonRechercher.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonRechercher.setCheckable(True)
        self.pushButtonRechercher.setObjectName("pushButtonRechercher")
        self.horizontalLayout.addWidget(self.pushButtonRechercher)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.PushButtonModifier = QtWidgets.QPushButton(self.QWidgetNavBar)
        self.PushButtonModifier.setMinimumSize(QtCore.QSize(50, 50))
        self.PushButtonModifier.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PushButtonModifier.setFont(font)
        self.PushButtonModifier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PushButtonModifier.setStyleSheet("background-color: rgb(26, 61, 119);\n"
"border-radius:5px;")
        self.PushButtonModifier.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/output-onlinepngtools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PushButtonModifier.setIcon(icon1)
        self.PushButtonModifier.setIconSize(QtCore.QSize(35, 35))
        self.PushButtonModifier.setCheckable(True)
        self.PushButtonModifier.setObjectName("PushButtonModifier")
        self.horizontalLayout.addWidget(self.PushButtonModifier)
        spacerItem4 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 3)
        self.horizontalLayout.setStretch(5, 1)
        self.gridLayout.addWidget(self.QWidgetNavBar, 1, 0, 1, 1)

        self.retranslateUi(QWdidgetSuivie)
        QtCore.QMetaObject.connectSlotsByName(QWdidgetSuivie)
        #show the window maximized
        QWdidgetSuivie.showMaximized()

    def retranslateUi(self, QWdidgetSuivie):
        _translate = QtCore.QCoreApplication.translate
        QWdidgetSuivie.setWindowTitle(_translate("QWdidgetSuivie", "membre"))
        self.label.setText(_translate("QWdidgetSuivie", "Suivie de développement d\'un athlète"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QWdidgetSuivie", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("QWdidgetSuivie", "Prénom"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("QWdidgetSuivie", "Sport"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("QWdidgetSuivie", "Poids"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("QWdidgetSuivie", "Ceinture"))
        self.lineEditNom.setPlaceholderText(_translate("QWdidgetSuivie", "Nom"))
        self.LineEditPrenom.setPlaceholderText(_translate("QWdidgetSuivie", "Prénom"))
import suivie_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QWdidgetSuivie = QtWidgets.QWidget()
    ui = Ui_QWdidgetSuivie()
    ui.setupUi(QWdidgetSuivie)
    QWdidgetSuivie.show()
    sys.exit(app.exec_())
