# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rh.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from lesCoaches.coaches import Ui_coaches
from gestionnaires.gestionnaire import Ui_gestionnaire
from lesMembres.membres import Ui_membres
class UI_MainWindowRh(object):
    def setupUi(self, MainWindowRh):
        MainWindowRh.setObjectName("MainWindowRh")
        MainWindowRh.resize(1045, 526)
        MainWindowRh.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindowRh)
        self.centralwidget.setStyleSheet("QWidget #centralwidget\n"
"{\n"
"border-image: url(:/background/image 1.png) 0 0 0 0 stretch stretch;\n"
"border-color: rgb(26, 61, 119);\n"
"border: solid 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(-1, 65, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(26, 61, 119);\n"
"                                        ")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_8.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(55, 40, 55, 40)
        self.horizontalLayout_2.setSpacing(55)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonMembres = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMembres.sizePolicy().hasHeightForWidth())
        self.pushButtonMembres.setSizePolicy(sizePolicy)
        self.pushButtonMembres.setMinimumSize(QtCore.QSize(253, 253))
        self.pushButtonMembres.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonMembres.setFont(font)
        self.pushButtonMembres.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMembres.setStyleSheet("border-radius: 10px;\n"
"                                                    border-top:2px solid;\n"
"                                                    border-color:rgb(26, 61, 119)\n"
"                                                ")
        self.pushButtonMembres.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/membres 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMembres.setIcon(icon)
        self.pushButtonMembres.setIconSize(QtCore.QSize(320, 250))
        self.pushButtonMembres.setCheckable(True)
        self.pushButtonMembres.setObjectName("pushButtonMembres")
        self.horizontalLayout_2.addWidget(self.pushButtonMembres)
        self.pushButtonCoaches = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCoaches.sizePolicy().hasHeightForWidth())
        self.pushButtonCoaches.setSizePolicy(sizePolicy)
        self.pushButtonCoaches.setMinimumSize(QtCore.QSize(253, 253))
        self.pushButtonCoaches.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonCoaches.setFont(font)
        self.pushButtonCoaches.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCoaches.setStyleSheet("border-radius: 10px;\n"
"                                                    border-top:2px solid;\n"
"                                                    border-color:rgb(26, 61, 119)\n"
"                                                ")
        self.pushButtonCoaches.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/coaches 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCoaches.setIcon(icon1)
        self.pushButtonCoaches.setIconSize(QtCore.QSize(320, 250))
        self.pushButtonCoaches.setCheckable(True)
        self.pushButtonCoaches.setObjectName("pushButtonCoaches")
        self.horizontalLayout_2.addWidget(self.pushButtonCoaches)
        self.pushButtonGest = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonGest.sizePolicy().hasHeightForWidth())
        self.pushButtonGest.setSizePolicy(sizePolicy)
        self.pushButtonGest.setMinimumSize(QtCore.QSize(253, 253))
        self.pushButtonGest.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonGest.setFont(font)
        self.pushButtonGest.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGest.setStyleSheet("border-radius: 10px;\n"
"                                                    border-top:2px solid;\n"
"                                                    border-color:rgb(26, 61, 119)\n"
"                                                ")
        self.pushButtonGest.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/gestionnaire 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGest.setIcon(icon2)
        self.pushButtonGest.setIconSize(QtCore.QSize(320, 250))
        self.pushButtonGest.setCheckable(True)
        self.pushButtonGest.setObjectName("pushButtonGest")
        self.horizontalLayout_2.addWidget(self.pushButtonGest)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addWidget(self.widget)
        self.pushButtonCoaches.clicked.connect(self.afficherCoaches)
        self.pushButtonGest.clicked.connect(self.afficherGestionnaire)
        self.pushButtonMembres.clicked.connect(self.afficherMembres)
        MainWindowRh.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowRh)
        QtCore.QMetaObject.connectSlotsByName(MainWindowRh)
        MainWindowRh.showMaximized()
        
    def retranslateUi(self, MainWindowRh):
        _translate = QtCore.QCoreApplication.translate
        MainWindowRh.setWindowTitle(_translate("MainWindowRh", "MainWindow"))
        self.label.setText(_translate("MainWindowRh", "Ressources Humaines"))

    def afficherCoaches(self):
            self.window = QtWidgets.QWidget()
            self.ui = Ui_coaches()
            self.ui.setupUi(self.window)
            self.window.show()

    def afficherGestionnaire(self):
            self.window = QtWidgets.QWidget()
            self.ui = Ui_gestionnaire()
            self.ui.setupUi(self.window)
            self.window.show()

    def afficherMembres(self):
            self.window = QtWidgets.QWidget()
            self.ui = Ui_membres()
            self.ui.setupUi(self.window)
            self.window.show()
from rhMenu import rh_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowRh = QtWidgets.QMainWindow()
    ui = UI_MainWindowRh()
    ui.setupUi(MainWindowRh)
    MainWindowRh.show()
    sys.exit(app.exec_())
