from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime, timedelta
from connexion_DB import connect_to_DB

class Ui_ajouterAbonnement(object):
    def setupUi(self, ajouterAbonnement):
        connection, cursor = connect_to_DB()
        ajouterAbonnement.setObjectName("ajouterAbonnement")
        ajouterAbonnement.resize(926, 570)
        ajouterAbonnement.setStyleSheet("background-color: rgb(219, 219, 219);")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ajouterAbonnement)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(ajouterAbonnement)
        self.widget.setStyleSheet("background-color: rgb(219, 219, 219);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(26, 61, 119);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setMinimumSize(QtCore.QSize(500, 20))
        self.widget_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/add.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.Nom = QtWidgets.QLabel(self.widget_6)
        self.Nom.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Nom.setFont(font)
        self.Nom.setStyleSheet("color: rgb(26, 61, 119);")
        self.Nom.setObjectName("Nom")
        self.verticalLayout_4.addWidget(self.Nom)
        self.lineEditNom = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditNom.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditNom.setSizeIncrement(QtCore.QSize(0, 0))

        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.lineEditNom.setFont(font)
        self.lineEditNom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditNom.setObjectName("lineEditNom")
        self.verticalLayout_4.addWidget(self.lineEditNom)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Prenom = QtWidgets.QLabel(self.widget_6)
        self.Prenom.setMinimumSize(QtCore.QSize(0, 35))
        self.Prenom.setFont(font)
        self.Prenom.setStyleSheet("color: rgb(26, 61, 119);")
        self.Prenom.setObjectName("Prenom")
        self.verticalLayout_4.addWidget(self.Prenom)
        self.lineEditPrenom = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditPrenom.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditPrenom.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.lineEditPrenom.setFont(font)
        self.lineEditPrenom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.verticalLayout_4.addWidget(self.lineEditPrenom)

        self.sport = QtWidgets.QLabel(self.widget_6)
        self.sport.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.sport.setFont(font)
        self.sport.setStyleSheet("color: rgb(26, 61, 119);")
        self.sport.setObjectName("sport")
        self.verticalLayout_4.addWidget(self.sport)
        self.dropdownSport = QtWidgets.QComboBox(self.widget_6)
        self.dropdownSport.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.dropdownSport.setFont(font)
        self.dropdownSport.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "color: rgb(83, 83, 83);")
        self.dropdownSport.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.dropdownSport.setObjectName("dropdownSport")
        self.dropdownSport.addItem("")
        self.verticalLayout_4.addWidget(self.dropdownSport)
        self.DateDebut = QtWidgets.QLabel(self.widget_6)
        self.DateDebut.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.DateDebut.setFont(font)
        self.DateDebut.setStyleSheet("color: rgb(26, 61, 119);")
        self.DateDebut.setObjectName("DateDebut")
        self.verticalLayout_4.addWidget(self.DateDebut)
        self.lineEditDateDebut = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditDateDebut.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditDateDebut.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.lineEditDateDebut.setFont(font)
        self.lineEditDateDebut.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditDateDebut.setObjectName("lineEditDateDebut")
        self.verticalLayout_4.addWidget(self.lineEditDateDebut)
        self.DateFin = QtWidgets.QLabel(self.widget_6)
        self.DateFin.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.DateFin.setFont(font)
        self.DateFin.setStyleSheet("color: rgb(26, 61, 119);")
        self.DateFin.setObjectName("DateFin")
        self.verticalLayout_4.addWidget(self.DateFin)
        self.lineEditDateFin = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditDateFin.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.lineEditDateFin.setFont(font)
        self.lineEditDateFin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditDateFin.setObjectName("lineEditDateFin")
        self.verticalLayout_4.addWidget(self.lineEditDateFin)
        self.Offre = QtWidgets.QLabel(self.widget_6)
        self.Offre.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Offre.setFont(font)
        self.Offre.setStyleSheet("color: rgb(26, 61, 119);")
        self.Offre.setObjectName("Offre")
        self.verticalLayout_4.addWidget(self.Offre)
        self.dropdownOffre = QtWidgets.QComboBox(self.widget_6)
        self.dropdownOffre.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.dropdownOffre.setFont(font)
        self.dropdownOffre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "color : rgb(83, 83, 83);")
        self.dropdownOffre.setObjectName("dropdownOffre")
        self.dropdownOffre.addItem("")
        self.verticalLayout_4.addWidget(self.dropdownOffre)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonSave = QtWidgets.QPushButton(self.widget_6)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButtonSave.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonSave.setStyleSheet("background-color: rgb(38, 255, 0);\n"
                                          "color: rgb(252, 252, 252);\n"
                                          "border-radius:5px;\n"
                                          "")
        self.pushButtonSave.setCheckable(True)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_3.addWidget(self.pushButtonSave)
        self.pushButtonAnnuler = QtWidgets.QPushButton(self.widget_6)
        self.pushButtonAnnuler.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButtonAnnuler.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonAnnuler.setFont(font)
        self.pushButtonAnnuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAnnuler.setStyleSheet("background-color: rgb(255, 93, 93);\n"
                                             "border-radius:5px;\n"
                                             "color: rgb(252, 252, 252);")
        self.pushButtonAnnuler.setCheckable(True)
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.horizontalLayout_3.addWidget(self.pushButtonAnnuler)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.horizontalLayout_2.addWidget(self.widget)

        self.retranslateUi(ajouterAbonnement)
        QtCore.QMetaObject.connectSlotsByName(ajouterAbonnement)

        query = "SELECT prix FROM offre WHERE sport = %s"
        sport1 = self.dropdownSport.currentText()
        cursor.execute(query, (sport1,))
        result = cursor.fetchone()
        prix_offre = 3
        self.dropdownOffre.addItem(str(prix_offre))

        date_debut = datetime.now().strftime("%Y-%m-%d")  ##########
        date_fin = (datetime.now() + timedelta(days=30)).strftime("%Y-%m-%d")
        self.lineEditDateDebut.setText(date_debut)
        self.lineEditDateFin.setText(date_fin)  ##############
        self.dropdownSport.currentTextChanged.connect(self.updateCombo2)
        self.pushButtonSave.clicked.connect(self.ajout)

    def retranslateUi(self, ajouterAbonnement):
        _translate = QtCore.QCoreApplication.translate
        ajouterAbonnement.setWindowTitle(_translate("ajouterAbonnement", "ajouterAbonnement"))
        self.label.setText(_translate("ajouterAbonnement", "Ajouter un Abonnement"))
        self.Nom.setText(_translate("ajouterAbonnement", "Nom"))
        self.lineEditNom.setPlaceholderText(_translate("ajouterAbonnement", " Nom"))
        self.Prenom.setText(_translate("ajouterAbonnement", "Prenom"))
        self.lineEditPrenom.setPlaceholderText(_translate("ajouterAbonnement", " Prenom"))
        self.sport.setText(_translate("ajouterAbonnement", "Sport"))
        self.dropdownSport.addItem("karate fille")
        self.dropdownSport.addItem("kick -16")
        self.dropdownSport.addItem("kick +16")
        self.dropdownSport.addItem("fitness N-Edd")
        self.dropdownSport.addItem("Karaté")
        self.dropdownSport.addItem("fitness hit")
        self.dropdownSport.addItem("kick walid")
        self.dropdownSport.addItem("self defense")
        self.dropdownSport.setItemText(0, _translate("ajouterAbonnement", "karate garcon"))
        self.DateDebut.setText(_translate("ajouterAbonnement", "Date de début"))

        self.DateFin.setText(_translate("ajouterAbonnement", "Date de fin"))
        self.Offre.setText(_translate("ajouterAbonnement", "prix"))
        self.pushButtonSave.setText(_translate("ajouterAbonnement", "Enregistrer"))
        self.pushButtonAnnuler.setText(_translate("ajouterAbonnement", "Annuler"))



    def updateCombo2(self):
        connection, cursor = connect_to_DB()
        self.dropdownOffre.clear()

        selected_value = self.dropdownSport.currentText()

        query = "SELECT prix FROM offre WHERE sport = %s"
        cursor.execute(query, (selected_value,))
        values = cursor.fetchall()

        for value in values:
            self.dropdownOffre.addItem(str(value[0]))

    def ajout(self):
        connection, cursor = connect_to_DB()

        Nom_adhérant = self.lineEditNom.text()
        Prenom_adhérant = self.lineEditPrenom.text()

        debut_abonnement = self.lineEditDateDebut.text()
        fin_abonnement = self.lineEditDateFin.text()

        cursor.execute("select ID from adhérant where nom = %s and prénom = %s", (Nom_adhérant, Prenom_adhérant))
        result = cursor.fetchone()  # Récupère la première ligne de résultat
        if result:
            id_adhérant = result[0]
            selected_value = self.dropdownSport.currentText()
            query = "SELECT ID_offre FROM offre WHERE sport = %s"
            cursor.execute(query, (selected_value,))
            current_offre = cursor.fetchone()

            if current_offre:
                current_offre_id = current_offre[0]

                query_insert = "INSERT INTO abonnement (ID_offre, ID_adhérant, date_début, date_fin) VALUES (%s, %s, %s, %s)"
                values = (current_offre_id, id_adhérant, debut_abonnement, fin_abonnement)

                try:
                    cursor.execute(query_insert, values)
                    connection.commit()
                    self.msg2 = QtWidgets.QMessageBox()
                    self.msg2.setIcon(QtWidgets.QMessageBox.Information)
                    self.msg2.setWindowTitle("Attention !")
                    self.msg2.setText("votre abonnement a été sajouté avec succes")
                    self.msg2.exec_()
                except mysql.connector.Error as err:
                    self.msg2 = QtWidgets.QMessageBox()
                    self.msg2.setWindowTitle("Attention !")
                    self.msg2.setIcon(QtWidgets.QMessageBox.Information)
                    self.msg2.setText("erreur lors de l'insertion des données")
                    self.msg2.exec_()
            else:
                self.msg2 = QtWidgets.QMessageBox()
                self.msg2.setWindowTitle("Attention !")
                self.msg2.setIcon(QtWidgets.QMessageBox.Information)
                self.msg2.setText("Aucune offre n'est sélectionné")
                self.msg2.exec_()
        else:
            self.msg2 = QtWidgets.QMessageBox()
            self.msg2.setIcon(QtWidgets.QMessageBox.Information)
            self.msg2.setWindowTitle("Attention !")
            self.msg2.setText("Aucun adhérant trouvé avec ce nom et prénom")
            self.msg2.exec_()

        # Fermez le curseur et la connexion à la base de données
        cursor.close()
        connection.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QWidget()
    ui = Ui_ajouterAbonnement()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())