# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\signinup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from login.login import Ui_DialogLogin as Ui_DialogLogin
from signup.signup import Ui_signup

class Ui_signinup(object):
    def setupUi(self, signinup):
        signinup.setObjectName("signinup")
        signinup.resize(910, 540)
        signinup.setStyleSheet("QWidget #signinup\n"
"{\n"
"background-color: rgb(217, 217, 217)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(signinup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background = QtWidgets.QWidget(signinup)
        self.background.setStyleSheet("QWidget #background{\n"
"border-image: url(:/background/image 1.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.background.setObjectName("background")
        self.gridLayout = QtWidgets.QGridLayout(self.background)
        self.gridLayout.setObjectName("gridLayout")
        self.box = QtWidgets.QWidget(self.background)
        self.box.setMinimumSize(QtCore.QSize(400, 300))
        self.box.setMaximumSize(QtCore.QSize(400, 300))
        self.box.setStyleSheet("QWidget #box{\n"
"background-color: rgb(248, 248, 248);\n"
"border-radius:15px;\n"
"}")
        self.box.setObjectName("box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.inscriptionconnexion = QtWidgets.QLabel(self.box)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.inscriptionconnexion.setFont(font)
        self.inscriptionconnexion.setStyleSheet("color: rgb(26, 61, 119);")
        self.inscriptionconnexion.setAlignment(QtCore.Qt.AlignCenter)
        self.inscriptionconnexion.setObjectName("inscriptionconnexion")
        self.verticalLayout_2.addWidget(self.inscriptionconnexion)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.voulezvous = QtWidgets.QLabel(self.box)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.voulezvous.setFont(font)
        self.voulezvous.setStyleSheet("color: rgb(127, 126, 131,60%);")
        self.voulezvous.setAlignment(QtCore.Qt.AlignCenter)
        self.voulezvous.setIndent(6)
        self.voulezvous.setObjectName("voulezvous")
        self.verticalLayout_2.addWidget(self.voulezvous)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.sinscrire = QtWidgets.QPushButton(self.box)
        self.sinscrire.setMinimumSize(QtCore.QSize(300, 30))
        self.sinscrire.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.sinscrire.setFont(font)
        self.sinscrire.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sinscrire.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(26, 61, 119);\n"
"border-radius:7px")
        self.sinscrire.setCheckable(True)
        self.sinscrire.setObjectName("sinscrire")
        self.verticalLayout_2.addWidget(self.sinscrire)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.ou = QtWidgets.QLabel(self.box)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ou.setFont(font)
        self.ou.setStyleSheet("color: rgb(127, 126, 131);")
        self.ou.setAlignment(QtCore.Qt.AlignCenter)
        self.ou.setObjectName("ou")
        self.verticalLayout_2.addWidget(self.ou)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.seconnecter = QtWidgets.QPushButton(self.box)
        self.seconnecter.setMinimumSize(QtCore.QSize(0, 30))
        self.seconnecter.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.seconnecter.setFont(font)
        self.seconnecter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seconnecter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(26, 61, 119);\n"
"border-radius:7px")
        self.seconnecter.setCheckable(True)
        self.seconnecter.setObjectName("seconnecter")
        self.verticalLayout_2.addWidget(self.seconnecter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout.addWidget(self.box, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.background)
        self.seconnecter.clicked.connect(self.connecter)
        self.sinscrire.clicked.connect(self.inscrire)
        self.retranslateUi(signinup)
        QtCore.QMetaObject.connectSlotsByName(signinup)
        self.signinup = signinup
    def connecter(self):
        if self.seconnecter.isChecked():
            self.signinup.close()
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_DialogLogin()
            self.ui.setupUi(self.window)
            self.window.show()
    def inscrire(self):
        if self.sinscrire.isChecked():
            self.signinup.close()
            self.window = QtWidgets.QDialog()
            self.ui = Ui_signup()
            self.ui.setupUi(self.window)
            self.window.show()



    def retranslateUi(self, signinup):
        _translate = QtCore.QCoreApplication.translate
        signinup.setWindowTitle(_translate("signinup", "Form"))
        self.inscriptionconnexion.setText(_translate("signinup", "Inscription / Connexion"))
        self.voulezvous.setText(_translate("signinup", "Voulez-vous s\'inscrire ou se connecter?"))
        self.sinscrire.setText(_translate("signinup", "S\'inscrire"))
        self.ou.setText(_translate("signinup", "ou"))
        self.seconnecter.setText(_translate("signinup", "Se connecter"))

import signin_signup_rc
import resources_login_rc
import signup_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signinup = QtWidgets.QWidget()
    ui = Ui_signinup()
    ui.setupUi(signinup)
    signinup.show()
    sys.exit(app.exec_())
