# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajouterMemberGroupe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from connexion_DB import connect_to_DB

class Ui_ajouterMembreGroupe(object):
    def __init__(self,ID_groupe):
        self.ID_groupe = ID_groupe


    def setupUi(self, ajouterMembreGroupe):
        ajouterMembreGroupe.setObjectName("ajouterMembreGroupe")
        ajouterMembreGroupe.resize(926, 570)
        ajouterMembreGroupe.setStyleSheet("background-color: rgb(219, 219, 219);")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ajouterMembreGroupe)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(ajouterMembreGroupe)
        self.widget.setStyleSheet("background-color: rgb(219, 219, 219);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(26, 61, 119);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setMinimumSize(QtCore.QSize(500, 20))
        self.widget_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Icon = QtWidgets.QLabel(self.widget_6)
        self.Icon.setMinimumSize(QtCore.QSize(50, 50))
        self.Icon.setMaximumSize(QtCore.QSize(50, 50))
        self.Icon.setText("")
        self.Icon.setPixmap(QtGui.QPixmap(":/icon/add.png"))
        self.Icon.setScaledContents(True)
        self.Icon.setObjectName("Icon")
        self.verticalLayout_4.addWidget(self.Icon)
        self.LabelNom = QtWidgets.QLabel(self.widget_6)
        self.LabelNom.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LabelNom.setFont(font)
        self.LabelNom.setStyleSheet("color: rgb(26, 61, 119);")
        self.LabelNom.setObjectName("LabelNom")
        self.verticalLayout_4.addWidget(self.LabelNom)
        self.lineEditNom = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditNom.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditNom.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.lineEditNom.setFont(font)
        self.lineEditNom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditNom.setObjectName("lineEditNom")
        self.verticalLayout_4.addWidget(self.lineEditNom)
        self.labelPrenom = QtWidgets.QLabel(self.widget_6)
        self.labelPrenom.setMinimumSize(QtCore.QSize(0, 35))
        self.labelPrenom.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrenom.setFont(font)
        self.labelPrenom.setStyleSheet("color: rgb(26, 61, 119);")
        self.labelPrenom.setObjectName("labelPrenom")
        self.verticalLayout_4.addWidget(self.labelPrenom)
        self.lineEditPrenom = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditPrenom.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditPrenom.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditPrenom.setFont(font)
        self.lineEditPrenom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPrenom.setObjectName("lineEditPrenom")
        self.verticalLayout_4.addWidget(self.lineEditPrenom)
        self.LabelPoids = QtWidgets.QLabel(self.widget_6)
        self.LabelPoids.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LabelPoids.setFont(font)
        self.LabelPoids.setStyleSheet("color: rgb(26, 61, 119);")
        self.LabelPoids.setObjectName("LabelPoids")
        self.verticalLayout_4.addWidget(self.LabelPoids)
        self.lineEditPoids = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditPoids.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEditPoids.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.lineEditPoids.setFont(font)
        self.lineEditPoids.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPoids.setObjectName("lineEditPoids")
        self.verticalLayout_4.addWidget(self.lineEditPoids)
        self.LabelAge = QtWidgets.QLabel(self.widget_6)
        self.LabelAge.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.LabelAge.setFont(font)
        self.LabelAge.setStyleSheet("color: rgb(26, 61, 119);")
        self.LabelAge.setObjectName("LabelAge")
        self.verticalLayout_4.addWidget(self.LabelAge)
        self.lineEditAge = QtWidgets.QLineEdit(self.widget_6)
        self.lineEditAge.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(13)
        self.lineEditAge.setFont(font)
        self.lineEditAge.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditAge.setObjectName("lineEditAge")
        self.verticalLayout_4.addWidget(self.lineEditAge)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonSave = QtWidgets.QPushButton(self.widget_6)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButtonSave.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonSave.setStyleSheet("background-color: rgb(38, 255, 0);\n"
"color: rgb(252, 252, 252);\n"
"border-radius:5px;\n"
"")
        self.pushButtonSave.setCheckable(True)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_3.addWidget(self.pushButtonSave)
        self.pushButtonAnnuler = QtWidgets.QPushButton(self.widget_6)
        self.pushButtonAnnuler.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButtonAnnuler.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonAnnuler.setFont(font)
        self.pushButtonAnnuler.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonAnnuler.setStyleSheet("background-color: rgb(255, 93, 93);\n"
"border-radius:5px;\n"
"color: rgb(252, 252, 252);")
        self.pushButtonAnnuler.setCheckable(True)
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.horizontalLayout_3.addWidget(self.pushButtonAnnuler)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.horizontalLayout_2.addWidget(self.widget)

        self.retranslateUi(ajouterMembreGroupe)
        QtCore.QMetaObject.connectSlotsByName(ajouterMembreGroupe)
        self.pushButtonSave.clicked.connect(self.ajoutMembreGroupe)


    def retranslateUi(self, ajouterMembreGroupe):
        _translate = QtCore.QCoreApplication.translate
        ajouterMembreGroupe.setWindowTitle(_translate("ajouterMembreGroupe", "ajouterMembreGroupe"))
        self.label.setText(_translate("ajouterMembreGroupe", "Ajouter un Membre au Groupe "+self.ID_groupe))
        self.LabelNom.setText(_translate("ajouterMembreGroupe", "Nom"))
        self.lineEditNom.setPlaceholderText(_translate("ajouterMembreGroupe", " Nom"))
        self.labelPrenom.setText(_translate("ajouterMembreGroupe", "Prénom"))
        self.lineEditPrenom.setPlaceholderText(_translate("ajouterMembreGroupe", "Prénom"))
        self.LabelPoids.setText(_translate("ajouterMembreGroupe", "Poids"))
        self.lineEditPoids.setPlaceholderText(_translate("ajouterMembreGroupe", "Poids"))
        self.LabelAge.setText(_translate("ajouterMembreGroupe", "Age"))
        self.lineEditAge.setPlaceholderText(_translate("ajouterMembreGroupe", "Age"))
        self.pushButtonSave.setText(_translate("ajouterMembreGroupe", "Enregistrer"))
        self.pushButtonAnnuler.setText(_translate("ajouterMembreGroupe", "Annuler"))

    def ajoutMembreGroupe(self):
        connection, cursor = connect_to_DB()

        nom = self.lineEditNom.text()
        prenom = self.lineEditPrenom.text()
        age = self.lineEditAge.text()
        poids = self.lineEditPoids.text()

        try:
            # Récupérer l'ID de l'adhérent
            cursor.execute("SELECT ID FROM adhérant WHERE nom = %s AND prénom = %s", (nom, prenom,))
            id_adherent = cursor.fetchone()

            if id_adherent:
                # Vérifier la validité de l'âge et du poids
                cursor.execute(
                    "SELECT EXISTS(SELECT * FROM groupes WHERE age_min < %s AND age_max > %s AND id_groupe = %s)",
                    (age, age, self.ID_groupe,))
                validite_age = cursor.fetchone()[0]

                cursor.execute(
                    "SELECT EXISTS(SELECT * FROM groupes WHERE poids_min < %s AND poids_max > %s AND id_groupe = %s)",
                    (poids, poids, self.ID_groupe,))
                validite_poids = cursor.fetchone()[0]
                cursor.execute("select exists(select * from groupes_adhérants WHERE id_groupe = %s and id_adhérant = %s)",(self.ID_groupe, id_adherent[0],))
                validite_id = cursor.fetchone()[0]
                if validite_age and validite_poids:

                  if validite_id == 0: # Ajouter le membre au groupe
                    cursor.execute("INSERT INTO groupes_adhérants VALUES (%s, %s, %s, %s)",
                                   (self.ID_groupe, id_adherent[0], poids, age,))
                    connection.commit()  # Valider la transaction
                    self.msg2 = QtWidgets.QMessageBox()
                    self.msg2.setWindowTitle("Attention !")
                    self.msg2.setIcon(QtWidgets.QMessageBox.Information)
                    self.msg2.setText(f"Membre ajouté au groupe avec succes")
                    self.msg2.exec_()
                  else:

                      self.msg2 = QtWidgets.QMessageBox()
                      self.msg2.setWindowTitle("Attention !")
                      self.msg2.setIcon(QtWidgets.QMessageBox.Information)
                      self.msg2.setText(f"cette personne existe deja dans ce groupe")
                      self.msg2.exec_()
                else:
                    # Afficher un message d'erreur
                    self.msg2 = QtWidgets.QMessageBox()
                    self.msg2.setIcon(QtWidgets.QMessageBox.Information)
                    self.msg2.setWindowTitle("Attention !")
                    if not validite_age:
                        self.msg2.setText("L'âge n'est pas valide")
                    else:
                        self.msg2.setText("Le poids n'est pas valide")
                    self.msg2.exec_()
            else:
                # Afficher un message si l'adhérent n'existe pas
                self.msg2 = QtWidgets.QMessageBox()
                self.msg2.setIcon(QtWidgets.QMessageBox.Information)
                self.msg2.setWindowTitle("Attention !")
                self.msg2.setText("Ce membre n'existe pas")
                self.msg2.exec_()

        except mysql.connector.Error as err:
            # Afficher le message d'erreur
            self.msg2 = QtWidgets.QMessageBox()
            self.msg2.setWindowTitle("Attention !")
            self.msg2.setIcon(QtWidgets.QMessageBox.Information)
            self.msg2.setText(f"Erreur lors de l'Ajout du membre : {err}")
            self.msg2.exec_()

        finally:
            # Fermez le curseur et la connexion à la base de données

            cursor.close()
            connection.close()


import ajouterMembreGroupe_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ajouterMembreGroupe = QtWidgets.QDialog()
    ui = Ui_ajouterMembreGroupe(QtWidgets)
    ui.setupUi(ajouterMembreGroupe)
    ajouterMembreGroupe.show()
    sys.exit(app.exec_())
